// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kehyxaqeybryrbjcvxuo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtlaHl4YXFleWJyeXJiamN2eHVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU1OTQ3NDcsImV4cCI6MjA1MTE3MDc0N30.jFLN4FEjZjwVvvxS6oYmMoD0NBI6fTiwHm6J38Fv1h0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);